# Generated by Django 5.2.7 on 2025-10-26 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngoprofile',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='ngo_docs/'),
        ),
        migrations.AddField(
            model_name='ngoprofile',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
    ]
