# Generated by Django 5.2.7 on 2025-10-26 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_ngoprofile_document_ngoprofile_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngoprofile',
            name='is_verification_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
