# Generated by Django 5.2.7 on 2025-10-26 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_ngoprofile_is_verification_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngoprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ngoprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
