# Generated by Django 5.2.7 on 2025-10-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_ngorequest'),
        ('users', '0004_ngoprofile_latitude_ngoprofile_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngoprofile',
            name='accepted_categories',
            field=models.ManyToManyField(blank=True, to='donations.category'),
        ),
    ]
