# Generated by Django 5.2.7 on 2025-11-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_donorprofile_latitude_donorprofile_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
